### ISSUE TITLE
RFI: Change build artifact names to avoid spaces

### ISSUE THREAD

**Issue by LannyRipple** [BTW-Community/btwDecoAddon2#25]
I use MacOS and Linux for play and it's a bit painful to deal with spaces in the Deco, API, and Terrain mods.  Would like to request that build artifacts be named with dashes instead of spaces in the names.

**Comment by ammoore00** [comment]
Yeah I can update naming schemes for the next release

**Comment by ammoore00** [comment]
Done for 2.13.4
