### ISSUE TITLE
RFI: Release on github

### ISSUE THREAD

**Issue by LannyRipple** [BTW-Community/btwDecoAddon2#28]
I'd like to request that Deco, Terrain, and the extended API be released on github.  I realize that MediaFire has been the historic release mechanism for BTW but trying to download Deco on new windows machine (for which I've loaded Privacy Badger but not Adblock Plus [don't see correct vendor.  Gods I hate MSWIN.]) I've got a popup from MediaFire that won't let me back out.

Will keep it short here but happy to chat about all the issues I see with current release mechanism if you have any interest.

**Comment by ammoore00** [comment]
Yeah I can definitely look into that. Never used github for releases but I can't imagine it would be terribly difficult. I should also set up the readmes to actually have proper documentation of the addons too.

**Comment by ammoore00** [comment]
Done for 2.13.4
