### ISSUE TITLE
Bug(?): Diamond sheers don't clip creepers

### ISSUE THREAD

**Issue by LannyRipple** [BTW-Community/btwDecoAddon2#29]
Playing BTW on Sock's community server season 4.  Have a pair of diamond sheers.  I'm 0 for 10 or 12 on trying to clip creepers with them.  I had sock grab himself a pair, go back into survival and clip one and he reports no issues.  Reporting this just in case it's a thing.

At first I thought it was a lag issue but with this many attempts I'm starting to doubt that.  They seem to clip everything else but (right click) just doesn't seem to do the snipping (for me).

Will keep testing and add any new information.

BTW 4-B0000003
BTW API 1.0
Deco 2.13.3
BTA 1.1.2

**Comment by ammoore00** [comment]
So the behavior is because my code is only being loaded when the creeper is loaded from a save file, but not when it is first spawned in. Still tracking down the cause of this bug.

**Comment by ammoore00** [comment]
Fixed for latest release (2.13.4)

**Comment by ammoore00** [comment]
Notably the root cause in the API replacement code has not been fixed but I just edited FC's base classes while I try and figure out that one.
