### ISSUE TITLE
Bug: Left clicking map in item frame logs you out, duplicates map

### ISSUE THREAD

**Issue by LannyRipple** [BTW-Community/btwDecoAddon2#30]
We have a map placed in an item frame on a wall in our base.  Left clicking the map will log you out of the game with an internal server error.  The map gets duplicated.  Doing this multiple times creates multiple duplicates but it's only possible for a player to pick up a single one.

BTW 4-B0000003
BTW API 1.0
Deco 2.13.3

**Comment by ammoore00** [comment]
Hmm i suspect some sort of desync with the server is happening. Will investigate.

**Comment by socklessthing** [comment]
Here is the log from the server console:
```
20.03 20:03:20 [Server] WARNING Failed to handle packet for Sockthing/00.000.000.00: java.lang.NullPointerException
20.03 20:03:20 [Server] INFO java.lang.NullPointerException
20.03 20:03:20 [Server] INFO at ns.b(SourceFile:138)
20.03 20:03:20 [Server] INFO at DecoEntityItemFrame.a(DecoEntityItemFrame.java:121)
20.03 20:03:20 [Server] INFO at DecoEntityItemFrame.a(DecoEntityItemFrame.java:44)
20.03 20:03:20 [Server] INFO at ne.j(EntityHanging.java:222)
20.03 20:03:20 [Server] INFO at sq.q(EntityPlayer.java:1184)
20.03 20:03:20 [Server] INFO at jh.a(NetServerHandler.java:776)
20.03 20:03:20 [Server] INFO at dr.a(SourceFile:36)
20.03 20:03:20 [Server] INFO at ci.b(SourceFile:350)
20.03 20:03:20 [Server] INFO at jh.d(NetServerHandler.java:77)
20.03 20:03:20 [Server] INFO at jk.b(SourceFile:35)
20.03 20:03:20 [Server] INFO at ie.b(SourceFile:30)
20.03 20:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:661)
20.03 20:03:20 [Server] INFO at hz.r(SourceFile:256)
20.03 20:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:559)
20.03 20:03:20 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
20.03 20:03:20 [Server] INFO at gp.run(SourceFile:573)
```
(edited out my IP)

**Comment by LannyRipple** [comment]
Extra info.  This is a problem, I believe, with item frames.  We have a clock I put in an item frame.  Decided to take it with me while placing some roads.  When I clicked the clock to remove from frame I was kicked out of game and when I logged back in the frame and clock were still in place but I had a new clock in inventory.

**Comment by ammoore00** [comment]
Fixed for next release. I had previously made changes to in DataWatcher on client because of that exact issue but apparently those never got applied to the server code.
