### ISSUE TITLE
Crashes due to accessing a private field, but only when run alongside BTW Cursed Fabric fork

### ISSUE THREAD

**Issue by rinOfTheStars** [BTW-Community/btwDecoAddon2#63]
What it says on the tin, basically. Crashes due to the deco grass class accessing a private field in a minecraft base class, likely due to failed reflection considering it doesn't crash if BTW Cursed Fabric Loader isn't present.

Log: https://paste.ee/p/BOm29
Occurred on the clientside mod version, while trying to update world from pre-BTW:CE 1.4.x to 1.4.1 with your recent release of BTA 3.x

**Comment by ammoore00** [comment]
Seems to be a load order issue and not related to fabric or deco.
