### ISSUE TITLE
Some items in Deco can't be crafted

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/btwDecoAddon2#69]
I don't know how to make pergola and dark prismarine blocks. I can't find any recipes in the crafting guide. Or do you get them by means other than crafting?

**Comment by upperman3** [comment]
I don't know how to make pergola and dark prismarine blocks. I can't find any recipes in the crafting guide. Or do you get them by means other than crafting?

**Comment by ammoore00** [comment]
Fixed for next release
