### ISSUE TITLE
Fir sub blocks are broken.

### ISSUE THREAD

**Issue by SterlingR3d** [BTW-Community/btwDecoAddon2#70]
Sawing fir drops 4 planks. Sawing a fir plank drops 2 fir siding. Placing the siding, it looks like molding. Sawing the fir siding that looks like molding results in 2 corners. Sawing a fir corner results in 2 fir corners. Trying to use a fir corner in a craft grid results in a crash. 

EDIT: btw ce 2.04, better terrain & better biomes 3.2, deco 4.1

**Comment by upperman3** [comment]
I have tried various things, but when I cut the deco tree, I think about various things.
Cutting Redwood yields an item named "Redwood Siding". but it looks like a fence.
If you cut it further, you will get an item named "Redwood corner", but it looks like a birch fence.
However, they all become Redwood corners when placed.
And crafting crashes the game.

I tried cutting other Deco trees, but I got something different from the original

**Comment by ammoore00** [comment]
Fixed for next release.
