### ISSUE TITLE
Mining a stone with a diamond pickaxe yields a smooth stone

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/btwDecoAddon2#73]
sorry if that's ok.
Digging stone with a diamond pickaxe normally yields cobblestone, but Deco yields smooth stone.

CE2.04
Deco4.1.1

**Comment by ammoore00** [comment]
Working as intended. By default, isolated stone drops smooth stone when mined with a diamond pick. There is a config option to make this always happen regardless of isolation, like sandstone in BTW

**Comment by upperman3** [comment]
i see
