### ISSUE TITLE
Deco has hardcore bounce enabled

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/btwDecoAddon2#76]
The so-called hardcore bounce of putting a block under your feet when you jump, which is possible in vanilla, is possible when Deco is added. Is this an intended adjustment?

**Comment by ammoore00** [comment]
Yes, that's intended. There is a config to disable placing while jumping in deco if you wish, but it is re-enabled by default since it interferes with building.

**Comment by upperman3** [comment]
I see
