### ISSUE TITLE
Crafting harf Deco wood breaks the game

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/btwDecoAddon2#81]
The game crashes when half wood is crafted on a workbench etc. with deco added wood
Crafts such as stairs, sticks, and decorative workbench were fine

**Comment by SterlingR3d** [comment]
Can confirm. Attempting to craft dark oak into fences from either moulding or planks crashes the game.

**Comment by upperman3** [comment]
I couldn't play the data I struggled with because of a bug. I'm too scared to play with this addon anymore.

**Comment by ammoore00** [comment]
Fixed for next release
